export enum Positions {
  GK = "GK",
  DEF = "DEF",
  MID = "MID",
  FWD = "FWD",
}
export type FootballPlayer = {
  id: string;
  name: string;
  club: string;
  price: number;
  totalpoints: number;
  position: Positions;
  image: string;
};

// export const footballplayers: FootballPlayer[] = [
//   {
//     id: 1,
//     name: "Brice Samba",
//     club: "arsenal",
//     price: 4,
//     position: Positions.GK,
//     totalpoints: 10,
//   },
//   {
//     id: 2,
//     name: "Mike Maignan",
//     club: "brighton",
//     price: 7,
//     position: Positions.GK,
//     totalpoints: 20,
//   },
//   {
//     id: 3,
//     name: "Alphonse Areola",
//     club: "westham",
//     price: 2,
//     position: Positions.GK,
//     totalpoints: 30,
//   },
//   // Defenders
//   {
//     id: 4,
//     name: "Ibrahima Konate",
//     club: "liverpool",
//     price: 3,
//     position: Positions.DEF,
//     totalpoints: 40,
//   },
//   {
//     id: 5,
//     name: "William Saliba",
//     club: "arsenal",
//     price: 5,
//     position: Positions.DEF,
//     totalpoints: 40,
//   },
//   {
//     id: 6,
//     name: "Jules Kounde",
//     club: "crystalpalace",
//     price: 8,
//     position: Positions.DEF,
//     totalpoints: 40,
//   },
//   {
//     id: 7,
//     name: "Dayot Upamecano",
//     club: "burnley",
//     price: 1,
//     position: Positions.DEF,
//     totalpoints: 30,
//   },
//   {
//     id: 8,
//     name: "Jonathan Clauss",
//     club: "fulham",
//     price: 6,
//     position: Positions.DEF,
//     totalpoints: 50,
//   },
//   {
//     id: 9,
//     name: "Benjamin Pavard",
//     club: "spurs",
//     price: 9,
//     position: Positions.DEF,
//     totalpoints: 0,
//   },
//   {
//     id: 10,
//     name: "Theo Hernandez",
//     club: "fulham",
//     price: 4,
//     position: Positions.DEF,
//     totalpoints: 0,
//   },
//   {
//     id: 11,
//     name: "Ferland Mendy",
//     club: "ipswich",
//     price: 7,
//     position: Positions.DEF,
//     totalpoints: 0,
//   },
//   // Midfielders
//   {
//     id: 12,
//     name: "N'Golo Kante",
//     club: "chelsea",
//     price: 2,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   {
//     id: 13,
//     name: "Eduardo Camavinga",
//     club: "newcastle",
//     price: 5,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   {
//     id: 14,
//     name: "Adrien Rabiot",
//     club: "liverpool",
//     price: 8,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   {
//     id: 15,
//     name: "Warren Zaire-Emery",
//     club: "mancity",
//     price: 1,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   {
//     id: 16,
//     name: "Youssouf Fofana",
//     club: "manunited",
//     price: 3,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   {
//     id: 17,
//     name: "Aurelien Tchouameni",
//     club: "mancity",
//     price: 6,
//     position: Positions.MID,
//     totalpoints: 0,
//   },
//   // Forwards
//   {
//     id: 18,
//     name: "Olivier Giroud",
//     club: "wolves",
//     price: 9,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 19,
//     name: "Antoine Griezmann",
//     club: "liverpool",
//     price: 4,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 20,
//     name: "Kylian Mbappe",
//     club: "mancity",
//     price: 7,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 21,
//     name: "Ousmane Dembele",
//     club: "nottingham",
//     price: 2,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 22,
//     name: "Randal Kolo Muani",
//     club: "bournemouth",
//     price: 5,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 23,
//     name: "Marcus Thuram",
//     club: "astonvilla",
//     price: 8,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 24,
//     name: "Bradley Barcola",
//     club: "arsenal",
//     price: 1,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
//   {
//     id: 25,
//     name: "Kingsley Coman",
//     club: "everton",
//     price: 6,
//     position: Positions.FWD,
//     totalpoints: 0,
//   },
// ];
